import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/** Creates a new form to create a point based on where the user right-clicks on the map
 *
 * @author Matthew Josephson
 */
public class createPOI extends javax.swing.JDialog {
    
    private final String[] ROOM_TYPES = {"Classroom", "Computer Lab", "Collaborative Room", "Mens Washroom", "Restaurant", "Unisex Washroom", "Womens Washroom", "Elevator", "Stairs", "Door"};

    private int x, y;
    private String pointType,pointName;
    
    /**
     * createPOI constructor. Creates new form createPOI
     * 
     * @param parent the parent frame for this dialog
     * @param modal specifies whether dialog blocks user input to other top-level windows when shown.
     * @param x the x-coordinate for the point of interest to be created.
     * @param y the y-coordinate for the point of interest to be created.
     * 
     */
    public createPOI(java.awt.Frame parent, boolean modal, int x, int y) {
        super(parent, modal);
        this.setTitle("Create Point");
        int[] mapPos = Map.getPosition();
        this.setLocation(700, 300);
        initComponents();
        iconSelected.setSelectedIndex(0);
        pointType = "Classroom";
        
        this.x = x;
        this.y = y;

        float scale = Map.getScale();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        makeName = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        iconSelected = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        selectIconLaber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        makeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeNameActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        iconSelected.setModel(new javax.swing.DefaultComboBoxModel<>(ROOM_TYPES));
        iconSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconSelectedActionPerformed(evt);
            }
        });

        nameLabel.setText("Enter a Name:");

        selectIconLaber.setText("Select an Icon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelButton)
                    .addComponent(nameLabel)
                    .addComponent(selectIconLaber))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(makeName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectIconLaber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Cancels the pop-up and point-creation */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Close the pop up
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Creates the new point */
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
       
        // Verify name is valid
        if (makeName.getText().isEmpty() && !AccountManager.getUser().equals("admin")) {
            // Set the border color to red to indicate an error
            makeName.setBorder(BorderFactory.createLineBorder(Color.RED));
            
            // Display an error message to the user
            JOptionPane.showMessageDialog(this, "Please enter a name for the point");
        }
        else if (makeName.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "The name must be less than 50 characters!");
        }
        else{
            pointName = makeName.getText();
            AccountManager.CreatePoint(x, y, pointName, pointType);
            this.dispose();
        }
        
    }//GEN-LAST:event_createButtonActionPerformed

    /** Sets the icon based on user selection */
    private void iconSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconSelectedActionPerformed
        //Sets the pointType variable to the selected item, which represents the type of point of interest.
        pointType = (String) iconSelected.getSelectedItem();
    }//GEN-LAST:event_iconSelectedActionPerformed

    /** Listener to set the text field based on user entry */
    private void makeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeNameActionPerformed
        //updates the pointName variable with the text entered by the user in the text field.
        pointName = makeName.getText();
    }//GEN-LAST:event_makeNameActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox<String> iconSelected;
    private javax.swing.JTextField makeName;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel selectIconLaber;
    // End of variables declaration//GEN-END:variables
}
